### ISSUE TITLE
Pre-release, hobby project, or ready for production?

### ISSUE THREAD

**Issue by panesofglass** [Ormikon/OWIN-Static#3]
I just found this project, and it looks like a much improved version of Microsoft.Owin.StaticFiles. I don't see a recent NuGet release, though. What's your roadmap? Thanks!

**Comment by Ormikon** [comment]
Hi @panesofglass! It's just my hobby (also used in some internal projects) but I planned to make it production ready. Yes, I have some changes without updating the package on NuGet, because I plan to cover some cases by tests before.
Roadmap:
- [ ] make some tests for existing functionality
- [ ] add new classes for loading static from the assembly resources
- [ ] add 'directory view' middleware
- [ ] make content type configurable
- [ ] add mutators (for ex. to mutate static markdown to html)
- [ ] *perf optimization

Thanks!

**Comment by panesofglass** [comment]
Very nice! I look forward to see where this goes!
